channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - bcftools =1.8
  - samtools =1.8
  - bwa =0.7
  - hisat2 =2.2.0
  - fastqc =0.11.9
  - stringtie =2.2.1
  - pandoc =2.18
