channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake-minimal>=5.24.1
  - samtools=1.7
  - hisat2=2.2.0
  - fastqc=0.11.9
  - stringtie=2.2.1
  - pandoc=2.18
  - pandas
  - sra-tools=2.8.0
